package loadgen

import (
	"bufio"
	"bytes"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"golang.org/x/net/http2/hpack"
)

// startH2CUpgradeServer runs the golang.org/x/net/http2/h2c handler on a
// loopback listener. The handler accepts the RFC 7540 §3.2 upgrade handshake
// out of the box, so we get a known-good counterpart for the happy-path
// integration-style test. Takes testing.TB so benchmarks can reuse it.
func startH2CUpgradeServer(tb testing.TB) (host, port string, cleanup func()) {
	tb.Helper()
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(200)
		_, _ = w.Write([]byte("OK"))
	})
	h2s := &http2.Server{MaxConcurrentStreams: 100}
	handler := h2c.NewHandler(mux, h2s)

	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		tb.Fatal(err)
	}

	srv := &http.Server{Handler: handler, ReadHeaderTimeout: 5 * time.Second}
	go func() { _ = srv.Serve(ln) }()
	h, p, _ := net.SplitHostPort(ln.Addr().String())
	return h, p, func() { _ = srv.Close(); _ = ln.Close() }
}

// TestH2CUpgradeAgainstH2CPackage verifies the full upgrade path end-to-end
// against golang.org/x/net/http2/h2c. A successful run proves that our wire
// format is compatible with a reference implementation.
//
// x/net/http2/hpack has a known data race during the upgrade handshake when
// the client sends SETTINGS_HEADER_TABLE_SIZE=0 (see golang/go#57639).
// That race lives in x/net, not loadgen, so we skip this test under -race.
func TestH2CUpgradeAgainstH2CPackage(t *testing.T) {
	if raceEnabled {
		t.Skip("skipping under -race: x/net/http2/hpack race on SETTINGS_HEADER_TABLE_SIZE=0 (golang/go#57639)")
	}
	host, port, cleanup := startH2CUpgradeServer(t)
	defer cleanup()

	cfg := testH2Cfg("GET", nil, nil, 1, 100)
	cfg.H2CUpgrade = true
	cfg.HTTP2 = false
	cfg.scheme = "http"

	client, err := newH2CUpgradeClient(host, port, "/", cfg)
	if err != nil {
		t.Fatalf("newH2CUpgradeClient: %v", err)
	}
	defer client.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	// Run a handful of requests — the first few after upgrade are the most
	// likely to trip stream-1-vs-stream-3 bugs.
	for i := range 20 {
		_, err := client.DoRequest(ctx, 0)
		if err != nil {
			t.Fatalf("DoRequest %d after upgrade: %v", i, err)
		}
	}
}

// TestH2CUpgradeHandshake asserts the wire format of the upgrade request
// generated by loadgen and then drives a minimal manual H2 handshake so we
// cover the code path without leaning on x/net.
func TestH2CUpgradeHandshake(t *testing.T) {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = ln.Close() }()

	host, port, _ := net.SplitHostPort(ln.Addr().String())

	var capturedReqLine, capturedConn, capturedUpgrade, capturedSettings string
	reqReceived := make(chan struct{}, 1)

	serverErrCh := make(chan error, 1)
	go func() {
		defer close(serverErrCh)
		conn, err := ln.Accept()
		if err != nil {
			serverErrCh <- fmt.Errorf("accept: %w", err)
			return
		}
		defer func() { _ = conn.Close() }()

		// Allow the whole exchange at most 5s.
		_ = conn.SetDeadline(time.Now().Add(5 * time.Second))

		br := bufio.NewReader(conn)
		// Request line
		line, err := br.ReadString('\n')
		if err != nil {
			serverErrCh <- fmt.Errorf("read request line: %w", err)
			return
		}
		capturedReqLine = strings.TrimRight(line, "\r\n")

		// Read headers until blank line.
		for {
			h, err := br.ReadString('\n')
			if err != nil {
				serverErrCh <- fmt.Errorf("read header: %w", err)
				return
			}
			trimmed := strings.TrimRight(h, "\r\n")
			if trimmed == "" {
				break
			}
			name, value, ok := strings.Cut(trimmed, ":")
			if !ok {
				continue
			}
			name = strings.ToLower(strings.TrimSpace(name))
			value = strings.TrimSpace(value)
			switch name {
			case "connection":
				capturedConn = value
			case "upgrade":
				capturedUpgrade = value
			case "http2-settings":
				capturedSettings = value
			}
		}
		select {
		case reqReceived <- struct{}{}:
		default:
		}

		// Send 101 Switching Protocols.
		_, _ = conn.Write([]byte("HTTP/1.1 101 Switching Protocols\r\n" +
			"Connection: Upgrade\r\n" +
			"Upgrade: h2c\r\n\r\n"))

		// Read the H2 client preface.
		prefaceBuf := make([]byte, len(h2ClientPreface))
		if _, err := io.ReadFull(br, prefaceBuf); err != nil {
			serverErrCh <- fmt.Errorf("read preface: %w", err)
			return
		}
		if string(prefaceBuf) != h2ClientPreface {
			serverErrCh <- fmt.Errorf("bad preface: %q", prefaceBuf)
			return
		}

		bw := bufio.NewWriter(conn)
		framer := newH2Framer(bw, br)

		// Read client SETTINGS (first frame post-preface must be SETTINGS).
		frame, err := framer.ReadFrame()
		if err != nil {
			serverErrCh <- fmt.Errorf("read client settings: %w", err)
			return
		}
		if frame.Type != frameSettings || frame.IsAck() {
			serverErrCh <- fmt.Errorf("expected SETTINGS, got type=%d ack=%v", frame.Type, frame.IsAck())
			return
		}

		// Drain anything else (WINDOW_UPDATE the client sends).
		_, _ = framer.ReadFrame()

		// Send server SETTINGS.
		if err := framer.WriteSettings([][2]uint32{
			{settingInitialWindowSize, 65535},
			{settingMaxFrameSize, 16384},
		}); err != nil {
			serverErrCh <- err
			return
		}
		if err := bw.Flush(); err != nil {
			serverErrCh <- err
			return
		}

		// Expect client SETTINGS ACK.
		for range 3 {
			f, err := framer.ReadFrame()
			if err != nil {
				serverErrCh <- fmt.Errorf("read frame after settings: %w", err)
				return
			}
			if f.Type == frameSettings && f.IsAck() {
				break
			}
		}

		// Ack our settings.
		if err := framer.WriteSettingsAck(); err != nil {
			serverErrCh <- err
			return
		}
		if err := bw.Flush(); err != nil {
			serverErrCh <- err
			return
		}

		// Send HEADERS + DATA for stream 1 (response to the upgrade GET).
		var hb bytes.Buffer
		henc := hpack.NewEncoder(&hb)
		_ = henc.WriteField(hpack.HeaderField{Name: ":status", Value: "200"})
		_ = henc.WriteField(hpack.HeaderField{Name: "content-length", Value: "2"})
		if err := framer.WriteHeaders(1, hb.Bytes(), false); err != nil {
			serverErrCh <- err
			return
		}
		if err := framer.WriteData(1, true, []byte("OK")); err != nil {
			serverErrCh <- err
			return
		}
		if err := bw.Flush(); err != nil {
			serverErrCh <- err
			return
		}

		// Now serve one more request on stream 3.
		for {
			f, err := framer.ReadFrame()
			if err != nil {
				return
			}
			if f.Type == frameHeaders {
				if f.StreamID == 1 {
					serverErrCh <- fmt.Errorf("client re-used stream ID 1 after upgrade")
					return
				}
				// Respond with 200 + DATA on the same stream.
				hb.Reset()
				_ = henc.WriteField(hpack.HeaderField{Name: ":status", Value: "200"})
				if err := framer.WriteHeaders(f.StreamID, hb.Bytes(), false); err != nil {
					return
				}
				if err := framer.WriteData(f.StreamID, true, []byte("OK")); err != nil {
					return
				}
				_ = bw.Flush()
				return
			}
		}
	}()

	cfg := testH2Cfg("GET", nil, nil, 1, 100)
	cfg.H2CUpgrade = true
	cfg.HTTP2 = false
	cfg.scheme = "http"

	client, err := newH2CUpgradeClient(host, port, "/bench", cfg)
	if err != nil {
		t.Fatalf("newH2CUpgradeClient: %v", err)
	}
	defer client.Close()

	select {
	case <-reqReceived:
	case <-time.After(5 * time.Second):
		t.Fatal("server never received upgrade request")
	}

	// Verify byte-for-byte wire format.
	if capturedReqLine != "GET /bench HTTP/1.1" {
		t.Errorf("wrong request line: %q", capturedReqLine)
	}
	// Connection header: must list both "Upgrade" and "HTTP2-Settings".
	if !hasToken(capturedConn, "Upgrade") || !hasToken(capturedConn, "HTTP2-Settings") {
		t.Errorf("Connection header missing required tokens: %q", capturedConn)
	}
	if !strings.EqualFold(capturedUpgrade, "h2c") {
		t.Errorf("Upgrade header: got %q want \"h2c\"", capturedUpgrade)
	}
	if capturedSettings == "" {
		t.Fatal("HTTP2-Settings header missing")
	}

	// Settings payload must be valid base64url-no-pad.
	decoded, err := base64.RawURLEncoding.DecodeString(capturedSettings)
	if err != nil {
		t.Fatalf("HTTP2-Settings base64url decode: %v", err)
	}
	if len(decoded)%6 != 0 {
		t.Fatalf("HTTP2-Settings payload length %d not a multiple of 6", len(decoded))
	}

	// Fire a real request to prove stream 3+ works.
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	if _, err := client.DoRequest(ctx, 0); err != nil {
		t.Fatalf("DoRequest after upgrade: %v", err)
	}

	select {
	case err := <-serverErrCh:
		if err != nil && !errors.Is(err, net.ErrClosed) && !errors.Is(err, io.EOF) {
			t.Errorf("server goroutine: %v", err)
		}
	case <-time.After(3 * time.Second):
		// Server may still be looping on ReadFrame; close the client to
		// tear it down.
	}
}

// TestH2CUpgradeRejected verifies that a server 400 to the upgrade request
// produces a specific error, not a generic EOF or stall.
func TestH2CUpgradeRejected(t *testing.T) {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = ln.Close() }()

	host, port, _ := net.SplitHostPort(ln.Addr().String())

	go func() {
		conn, err := ln.Accept()
		if err != nil {
			return
		}
		defer func() { _ = conn.Close() }()
		br := bufio.NewReader(conn)
		// Drain until CRLF CRLF so the client's write doesn't block.
		for {
			line, err := br.ReadString('\n')
			if err != nil {
				return
			}
			if line == "\r\n" || line == "\n" {
				break
			}
		}
		_, _ = conn.Write([]byte("HTTP/1.1 400 Bad Request\r\nContent-Length: 0\r\n\r\n"))
	}()

	cfg := testH2Cfg("GET", nil, nil, 1, 100)
	cfg.H2CUpgrade = true
	cfg.scheme = "http"

	_, err = newH2CUpgradeClient(host, port, "/", cfg)
	if err == nil {
		t.Fatal("expected upgrade error, got nil")
	}
	msg := err.Error()
	if !strings.Contains(msg, "400") && !strings.Contains(strings.ToLower(msg), "upgrade") {
		t.Errorf("error should mention 400 or upgrade, got %q", msg)
	}
}

// TestH2CUpgradeMissingHeaders verifies that a 101 response without the
// correct Upgrade / Connection headers is treated as a protocol violation.
func TestH2CUpgradeMissingHeaders(t *testing.T) {
	cases := []struct {
		name    string
		headers string
		wantSub string
	}{
		{
			name:    "no upgrade header",
			headers: "Connection: Upgrade\r\n",
			wantSub: "upgrade",
		},
		{
			name:    "wrong upgrade protocol",
			headers: "Connection: Upgrade\r\nUpgrade: websocket\r\n",
			wantSub: "upgrade",
		},
		{
			name:    "connection header without upgrade token",
			headers: "Connection: keep-alive\r\nUpgrade: h2c\r\n",
			wantSub: "connection",
		},
		{
			name:    "200 instead of 101",
			headers: "",
			wantSub: "101",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			ln, err := net.Listen("tcp", "127.0.0.1:0")
			if err != nil {
				t.Fatal(err)
			}
			defer func() { _ = ln.Close() }()
			host, port, _ := net.SplitHostPort(ln.Addr().String())

			go func() {
				conn, err := ln.Accept()
				if err != nil {
					return
				}
				defer func() { _ = conn.Close() }()
				br := bufio.NewReader(conn)
				for {
					line, err := br.ReadString('\n')
					if err != nil {
						return
					}
					if line == "\r\n" || line == "\n" {
						break
					}
				}
				if tc.name == "200 instead of 101" {
					_, _ = conn.Write([]byte("HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n"))
					return
				}
				_, _ = conn.Write([]byte("HTTP/1.1 101 Switching Protocols\r\n" + tc.headers + "\r\n"))
			}()

			cfg := testH2Cfg("GET", nil, nil, 1, 100)
			cfg.H2CUpgrade = true
			cfg.scheme = "http"

			_, err = newH2CUpgradeClient(host, port, "/", cfg)
			if err == nil {
				t.Fatalf("expected error, got nil")
			}
			if !strings.Contains(strings.ToLower(err.Error()), tc.wantSub) {
				t.Errorf("error %q should contain %q", err.Error(), tc.wantSub)
			}
		})
	}
}

// TestH2CUpgradeTLSRejected verifies that attempting h2c-upgrade over TLS
// fails immediately with a clear message (h2c over TLS is undefined).
func TestH2CUpgradeTLSRejected(t *testing.T) {
	cfg := testH2Cfg("GET", nil, nil, 1, 100)
	cfg.H2CUpgrade = true
	cfg.scheme = "https"

	_, err := newH2CUpgradeClient("localhost", "443", "/", cfg)
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !strings.Contains(err.Error(), "TLS") && !strings.Contains(strings.ToLower(err.Error()), "cleartext") {
		t.Errorf("error should mention TLS/cleartext, got %q", err.Error())
	}
}

// TestH2CUpgradeStressAfterHandshake drives many concurrent requests after
// the upgrade to ensure stream 1 handling does not break the H2 multiplexer.
// See TestH2CUpgradeAgainstH2CPackage for why this is skipped under -race.
func TestH2CUpgradeStressAfterHandshake(t *testing.T) {
	if raceEnabled {
		t.Skip("skipping under -race: x/net/http2/hpack race (golang/go#57639)")
	}
	host, port, cleanup := startH2CUpgradeServer(t)
	defer cleanup()

	cfg := testH2Cfg("GET", nil, nil, 2, 50)
	cfg.H2CUpgrade = true
	cfg.HTTP2 = false
	cfg.scheme = "http"

	client, err := newH2CUpgradeClient(host, port, "/", cfg)
	if err != nil {
		t.Fatalf("newH2CUpgradeClient: %v", err)
	}
	defer client.Close()

	benchCtx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	var wg sync.WaitGroup
	var okCount, errCount atomic.Int64
	for w := range 50 {
		wg.Add(1)
		go func(id int) {
			defer wg.Done()
			for benchCtx.Err() == nil {
				_, err := client.DoRequest(benchCtx, id)
				if err != nil {
					if benchCtx.Err() != nil {
						return
					}
					errCount.Add(1)
				} else {
					okCount.Add(1)
				}
			}
		}(w)
	}
	wg.Wait()
	if okCount.Load() == 0 {
		t.Fatalf("zero successes: err=%d", errCount.Load())
	}
	t.Logf("upgrade stress: %d OK, %d errors", okCount.Load(), errCount.Load())
}

// TestBuildH2CUpgradeRequestHostCanonical verifies the Host header follows
// RFC 9110 §7.2: the port is omitted when it matches the scheme default.
// Previously loadgen always included the port — some strict servers treat
// "example.com:80" as non-canonical and may reject it.
func TestBuildH2CUpgradeRequestHostCanonical(t *testing.T) {
	cases := []struct {
		name   string
		host   string
		port   string
		scheme string
		want   string
	}{
		{"http default port stripped", "example.com", "80", "http", "Host: example.com\r\n"},
		{"http non-default port kept", "example.com", "8080", "http", "Host: example.com:8080\r\n"},
		{"https default port stripped", "example.com", "443", "https", "Host: example.com\r\n"},
		{"https non-default port kept", "example.com", "8443", "https", "Host: example.com:8443\r\n"},
		{"loopback non-default port kept", "127.0.0.1", "12345", "http", "Host: 127.0.0.1:12345\r\n"},
		{"empty port omitted", "example.com", "", "http", "Host: example.com\r\n"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			req := buildH2CUpgradeRequest("/", tc.host, tc.port, tc.scheme, []byte{0, 0, 0, 0, 0, 0})
			if !bytes.Contains(req, []byte(tc.want)) {
				t.Errorf("request missing %q\n---\n%s\n---", tc.want, req)
			}
			// Regression guard: never emit ":<default-port>" in the Host line.
			if tc.scheme == "http" && tc.port == "80" && bytes.Contains(req, []byte("Host: example.com:80")) {
				t.Error("http default port 80 must be stripped")
			}
			if tc.scheme == "https" && tc.port == "443" && bytes.Contains(req, []byte("Host: example.com:443")) {
				t.Error("https default port 443 must be stripped")
			}
		})
	}
}

// hasToken reports whether a comma-separated header list contains token
// (case-insensitive, leading/trailing whitespace tolerant).
func hasToken(list, token string) bool {
	for part := range strings.SplitSeq(list, ",") {
		if strings.EqualFold(strings.TrimSpace(part), token) {
			return true
		}
	}
	return false
}
